# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 09:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ('begin_date', 'end_date'),
            },
        ),
    ]
