# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_modal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
