# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_modal', '0002_auto_20180722_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
