# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-28 19:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('scheduled_modal', '0003_auto_20180722_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name=b'intitul\xc3\xa9')),
            ],
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-begin_date', '-end_date'), 'verbose_name': 'Annonce (popup)', 'verbose_name_plural': 'Annonces (popup)'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='begin_date',
            field=models.DateField(verbose_name=b'date de d\xc3\xa9but'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(verbose_name=b'date de fin'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='show_period',
            field=models.BooleanField(default=False, verbose_name=b'p\xc3\xa9riode affich\xc3\xa9e'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name=b'contenu'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'titre'),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduled_modal.Announcement'),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='file',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name=b'fichier'),
        ),
    ]
